# Generated by Django 5.2.1 on 2025-05-13 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='tx_title', max_length=100, verbose_name='Titulo')),
                ('amount', models.DecimalField(db_column='nb_amount', decimal_places=2, max_digits=10, verbose_name='Quanto')),
                ('description', models.CharField(blank=True, db_column='tx_description', max_length=100, verbose_name='Descrição')),
                ('date', models.DateField(db_column='dt_date', verbose_name='Data')),
                ('category', models.CharField(choices=[('groceries', 'Alimentação'), ('leisure', 'Lazer'), ('electronics', 'Eletrônicos'), ('utilities', 'Contas'), ('clothing', 'Roupas'), ('health', 'Saúde'), ('others', 'Outros')], db_column='tx_category', max_length=20, verbose_name='Categoria')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
