# Generated by Django 5.2.1 on 2025-05-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(db_column='nb_amount', decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
